chore. there is an unexpected browser dom only type in the newer @types/node::stream.d.ts causing error TS2304: Cannot find name 'Blob'. thus we enable skipLibCheck for now and do not statically validate the internal types of the libs depended on.